/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Aggregates": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Application": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "CLERK_PUBLISHABLE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLERK_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CONTACT_FROM_ADDRESS": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CONTACT_TO_ADDRESS": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Marketing": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "NEXT_PUBLIC_TURNSTILE_SITE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RESEND_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Router": {
      "type": "sst.aws.Router"
      "url": string
    }
    "TURNSTILE_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TWITTER_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Tokens": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Tweets": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "UserData": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "WEB_DOMAIN": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}

import "sst"
export {}