export const clerkAppearance = {
  variables: {
    colorPrimary:        '#FF6B2C',
    colorBackground:     '#14110D',
    colorInputBackground:'#1F1B14',
    colorInputText:      '#F6E9D4',
    colorText:           '#F6E9D4',
    colorTextSecondary:  '#A39378',
    colorTextOnPrimaryBackground: '#F6E9D4',
    colorDanger:         '#C8462E',
    colorSuccess:        '#4F8A4A',
    colorNeutral:        '#A3A3AB',
    borderRadius:        '6px',
    fontFamily:          'var(--font-sans)',
    fontFamilyButtons:   'var(--font-sans)',
    fontSize:            '14px',
  },
  elements: {
    card:            'bg-[#1F1B14] shadow-none border border-[#2A2620]',
    headerTitle:     'text-[#F6E9D4]',
    headerSubtitle:  'text-[#A39378]',
    socialButtonsBlockButton: 'border-[#2A2620] bg-[#1F1B14] text-[#F6E9D4] hover:bg-[#25201A]',
    formFieldInput:  'border-[#2A2620] bg-[#1F1B14] text-[#F6E9D4] focus:border-[#FF6B2C]',
    formFieldLabel:  'text-[#C9B894]',
    footerActionLink:'text-[#FF6B2C] hover:text-[#FF7E45]',
    identityPreviewText: 'text-[#F6E9D4]',
    identityPreviewEditButton: 'text-[#FF6B2C]',
  },
}
